#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("MenuBuddySample.Android.Resource", IsApplication=true)]

namespace MenuBuddySample.Android
{
	
	
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::FilenameBuddy.Android.Resource.String.ApplicationName = global::MenuBuddySample.Android.Resource.String.ApplicationName;
			global::FilenameBuddy.Android.Resource.String.Hello = global::MenuBuddySample.Android.Resource.String.Hello;
			global::FontBuddyLib.Android.Resource.String.ApplicationName = global::MenuBuddySample.Android.Resource.String.ApplicationName;
			global::FontBuddyLib.Android.Resource.String.Hello = global::MenuBuddySample.Android.Resource.String.Hello;
			global::GameTimer.Android.Resource.String.ApplicationName = global::MenuBuddySample.Android.Resource.String.ApplicationName;
			global::GameTimer.Android.Resource.String.Hello = global::MenuBuddySample.Android.Resource.String.Hello;
			global::HadoukInput.Android.Resource.String.ApplicationName = global::MenuBuddySample.Android.Resource.String.ApplicationName;
			global::HadoukInput.Android.Resource.String.Hello = global::MenuBuddySample.Android.Resource.String.Hello;
			global::InputHelper.Android.Resource.String.ApplicationName = global::MenuBuddySample.Android.Resource.String.ApplicationName;
			global::InputHelper.Android.Resource.String.Hello = global::MenuBuddySample.Android.Resource.String.Hello;
			global::MatrixExtensions.Android.Resource.String.ApplicationName = global::MenuBuddySample.Android.Resource.String.ApplicationName;
			global::MatrixExtensions.Android.Resource.String.Hello = global::MenuBuddySample.Android.Resource.String.Hello;
			global::MouseBuddy.Android.Resource.String.ApplicationName = global::MenuBuddySample.Android.Resource.String.ApplicationName;
			global::MouseBuddy.Android.Resource.String.Hello = global::MenuBuddySample.Android.Resource.String.Hello;
			global::PrimitiveBuddy.Android.Resource.String.ApplicationName = global::MenuBuddySample.Android.Resource.String.ApplicationName;
			global::PrimitiveBuddy.Android.Resource.String.Hello = global::MenuBuddySample.Android.Resource.String.Hello;
			global::RandomExtensions.Android.Resource.String.ApplicationName = global::MenuBuddySample.Android.Resource.String.ApplicationName;
			global::RandomExtensions.Android.Resource.String.Hello = global::MenuBuddySample.Android.Resource.String.Hello;
			global::ResolutionBuddy.Android.Resource.String.ApplicationName = global::MenuBuddySample.Android.Resource.String.ApplicationName;
			global::ResolutionBuddy.Android.Resource.String.Hello = global::MenuBuddySample.Android.Resource.String.Hello;
			global::StateMachineBuddy.Android.Resource.String.ApplicationName = global::MenuBuddySample.Android.Resource.String.ApplicationName;
			global::StateMachineBuddy.Android.Resource.String.Hello = global::MenuBuddySample.Android.Resource.String.Hello;
			global::TouchScreenBuddy.Android.Resource.String.ApplicationName = global::MenuBuddySample.Android.Resource.String.ApplicationName;
			global::TouchScreenBuddy.Android.Resource.String.Hello = global::MenuBuddySample.Android.Resource.String.Hello;
			global::Vector2Extensions.Android.Resource.String.ApplicationName = global::MenuBuddySample.Android.Resource.String.ApplicationName;
			global::Vector2Extensions.Android.Resource.String.Hello = global::MenuBuddySample.Android.Resource.String.Hello;
			global::XmlBuddy.Android.Resource.String.ApplicationName = global::MenuBuddySample.Android.Resource.String.ApplicationName;
			global::XmlBuddy.Android.Resource.String.Hello = global::MenuBuddySample.Android.Resource.String.Hello;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7F010000
			public const int Icon = 2130771968;
			
			// aapt resource value: 0x7F010001
			public const int leak_canary_icon = 2130771969;
			
			// aapt resource value: 0x7F010002
			public const int leak_canary_notification = 2130771970;
			
			// aapt resource value: 0x7F010003
			public const int leak_canary_toast_background = 2130771971;
			
			// aapt resource value: 0x7F010004
			public const int Splash = 2130771972;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7F020000
			public const int leak_canary_action = 2130837504;
			
			// aapt resource value: 0x7F020001
			public const int leak_canary_display_leak_failure = 2130837505;
			
			// aapt resource value: 0x7F020002
			public const int leak_canary_display_leak_list = 2130837506;
			
			// aapt resource value: 0x7F020003
			public const int leak_canary_row_connector = 2130837507;
			
			// aapt resource value: 0x7F020004
			public const int leak_canary_row_more = 2130837508;
			
			// aapt resource value: 0x7F020005
			public const int leak_canary_row_text = 2130837509;
			
			// aapt resource value: 0x7F020006
			public const int leak_canary_row_time = 2130837510;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7F030000
			public const int leak_canary_display_leak = 2130903040;
			
			// aapt resource value: 0x7F030001
			public const int leak_canary_heap_dump_toast = 2130903041;
			
			// aapt resource value: 0x7F030002
			public const int leak_canary_leak_row = 2130903042;
			
			// aapt resource value: 0x7F030003
			public const int leak_canary_ref_row = 2130903043;
			
			// aapt resource value: 0x7F030004
			public const int leak_canary_ref_top_row = 2130903044;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7F040000
			public const int ApplicationName = 2130968576;
			
			// aapt resource value: 0x7F040001
			public const int Hello = 2130968577;
			
			// aapt resource value: 0x7F040002
			public const int leak_canary_analysis_failed = 2130968578;
			
			// aapt resource value: 0x7F040003
			public const int leak_canary_class_has_leaked = 2130968579;
			
			// aapt resource value: 0x7F040004
			public const int leak_canary_could_not_save_text = 2130968580;
			
			// aapt resource value: 0x7F040005
			public const int leak_canary_could_not_save_title = 2130968581;
			
			// aapt resource value: 0x7F040006
			public const int leak_canary_delete = 2130968582;
			
			// aapt resource value: 0x7F040007
			public const int leak_canary_delete_all = 2130968583;
			
			// aapt resource value: 0x7F040008
			public const int leak_canary_delete_all_leaks_title = 2130968584;
			
			// aapt resource value: 0x7F040009
			public const int leak_canary_display_activity_label = 2130968585;
			
			// aapt resource value: 0x7F04000A
			public const int leak_canary_excluded_row = 2130968586;
			
			// aapt resource value: 0x7F04000B
			public const int leak_canary_failure_report = 2130968587;
			
			// aapt resource value: 0x7F04000C
			public const int leak_canary_leak_excluded = 2130968588;
			
			// aapt resource value: 0x7F04000D
			public const int leak_canary_leak_list_title = 2130968589;
			
			// aapt resource value: 0x7F040010
			public const int leak_canary_notification_message = 2130968592;
			
			// aapt resource value: 0x7F04000E
			public const int leak_canary_no_leak_text = 2130968590;
			
			// aapt resource value: 0x7F04000F
			public const int leak_canary_no_leak_title = 2130968591;
			
			// aapt resource value: 0x7F040012
			public const int leak_canary_permission_notification_text = 2130968594;
			
			// aapt resource value: 0x7F040013
			public const int leak_canary_permission_notification_title = 2130968595;
			
			// aapt resource value: 0x7F040011
			public const int leak_canary_permission_not_granted = 2130968593;
			
			// aapt resource value: 0x7F040014
			public const int leak_canary_share_heap_dump = 2130968596;
			
			// aapt resource value: 0x7F040015
			public const int leak_canary_share_leak = 2130968597;
			
			// aapt resource value: 0x7F040016
			public const int leak_canary_share_with = 2130968598;
			
			// aapt resource value: 0x7F040017
			public const int leak_canary_storage_permission_activity_label = 2130968599;
			
			// aapt resource value: 0x7F040018
			public const int leak_canary_toast_heap_dump = 2130968600;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7F050001
			public const int leak_canary_LeakCanary_Base = 2131034113;
			
			// aapt resource value: 0x7F050002
			public const int leak_canary_Theme_Transparent = 2131034114;
			
			// aapt resource value: 0x7F050000
			public const int Theme_Splash = 2131034112;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
